apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: My Homelab Dashboard
    theme: dark
    color: slate
  services.yaml: |
    - Infrastructure:
      - Kubernetes Dashboard:
        href: https://kubernetes-dashboard.local
        description: Kubernetes Dashboard
        icon: simple-icons:kubernetes
      - Grafana:
        href: https://grafana.local
        description: Metrics and Dashboards
        icon: simple-icons:grafana
      - Prometheus:
        href: https://prometheus.local
        description: Monitoring
        icon: simple-icons:prometheus
    - Media:
      - Plex:
        href: https://plex.local
        description: Media Server
        icon: simple-icons:plex
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Development:
      - GitHub:
        - abbr: GH
          href: https://github.com/
  docker.yaml: ""