apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Metadata for the kustomization
metadata:
  name: homepage-base

# List of resources to include
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml

# Common labels to apply to all resources
commonLabels:
  app: homepage
  app.kubernetes.io/name: homepage
  app.kubernetes.io/instance: homepage
  app.kubernetes.io/managed-by: kustomize

# Configure the ConfigMap generation
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    behavior: merge
    files:
      - kubernetes.yaml=configs/kubernetes.yaml
      - settings.yaml=configs/settings.yaml
      - services.yaml=configs/services.yaml
      - widgets.yaml=configs/widgets.yaml
      - bookmarks.yaml=configs/bookmarks.yaml
      - docker.yaml=configs/docker.yaml

# Images to use
images:
  - name: ghcr.io/gethomepage/homepage
    newTag: latest