apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  
  settings.yaml: |
    title: "CBunna's Home Lab"
    favicon: "/images/favicon.ico"
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Personal:
        style: row
        columns: 4
      Media:
        style: row
        columns: 3
      Infrastructure:
        style: row
        columns: 4
      Monitoring:
        style: row
        columns: 3
    providers:
      kubernetes:
        mode: cluster
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false
      hideVisitURL: false
    showStats: true
    statusStyle: dot
    hideVersion: false
  
  services.yaml: |
    - Personal:
        - Nextcloud:
            href: https://nextcloud.local
            description: Personal cloud storage
            icon: nextcloud.png
            namespace: nextcloud
            app: nextcloud
            widget:
              type: nextcloud
              url: https://nextcloud.local
              username: "{{HOMEPAGE_VAR_NEXTCLOUD_USER}}"
              password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASS}}"
        
        - Vaultwarden:
            href: https://vault.local
            description: Password manager
            icon: bitwarden.png
            namespace: security
            app: vaultwarden
            widget:
              type: vaultwarden
              url: https://vault.local
    
    - Media:
        - Plex:
            href: https://plex.local
            description: Media server
            icon: plex.png
            namespace: media
            app: plex
            widget:
              type: plex
              url: https://plex.local
              key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
        
        - Jellyfin:
            href: https://jellyfin.local
            description: Alternative media server
            icon: jellyfin.png
            namespace: media
            app: jellyfin
            widget:
              type: jellyfin
              url: https://jellyfin.local
              username: "{{HOMEPAGE_VAR_JELLYFIN_USER}}"
              password: "{{HOMEPAGE_VAR_JELLYFIN_PASS}}"
        
        - Transmission:
            href: https://transmission.local
            description: BitTorrent client
            icon: transmission.png
            namespace: media
            app: transmission
            widget:
              type: transmission
              url: https://transmission.local
              username: "{{HOMEPAGE_VAR_TRANSMISSION_USER}}"
              password: "{{HOMEPAGE_VAR_TRANSMISSION_PASS}}"
    
    - Infrastructure:
        - Proxmox:
            href: https://proxmox.local:8006
            description: Virtualization platform
            icon: proxmox.png
            widget:
              type: proxmox
              url: https://proxmox.local:8006
              username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_PASS}}"
        
        - Portainer:
            href: https://portainer.local
            description: Container management
            icon: portainer.png
            namespace: portainer
            app: portainer
            widget:
              type: portainer
              url: https://portainer.local
              env: 2
              key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
        
        - TrueNAS:
            href: https://truenas.local
            description: Network attached storage
            icon: truenas.png
            widget:
              type: truenas
              url: https://truenas.local
              username: "{{HOMEPAGE_VAR_TRUENAS_USER}}"
              password: "{{HOMEPAGE_VAR_TRUENAS_PASS}}"
        
        - pfSense:
            href: https://pfsense.local
            description: Firewall and router
            icon: pfsense.png
            widget:
              type: pfsense
              url: https://pfsense.local
              username: "{{HOMEPAGE_VAR_PFSENSE_USER}}"
              password: "{{HOMEPAGE_VAR_PFSENSE_PASS}}"
    
    - Monitoring:
        - Grafana:
            href: https://grafana.local
            description: Monitoring dashboards
            icon: grafana.png
            namespace: monitoring
            app: grafana
            widget:
              type: grafana
              url: https://grafana.local
              username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
              password: "{{HOMEPAGE_VAR_GRAFANA_PASS}}"
        
        - Prometheus:
            href: https://prometheus.local
            description: Metrics collection
            icon: prometheus.png
            namespace: monitoring
            app: prometheus
            widget:
              type: prometheus
              url: https://prometheus.local
        
        - Uptime Kuma:
            href: https://uptime.local
            description: Uptime monitoring
            icon: uptime-kuma.png
            namespace: monitoring
            app: uptime-kuma
            widget:
              type: uptimekuma
              url: https://uptime.local
              slug: "{{HOMEPAGE_VAR_UPTIMEKUMA_SLUG}}"
  
  widgets.yaml: |
    - logo:
        icon: /images/logo.png
    
    - greeting:
        text_size: xl
        text: "Welcome to CBunna's Home Lab"
    
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
    
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "K8s Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    
    - openweathermap:
        label: Prague
        latitude: 50.0755
        longitude: 14.4378
        units: metric
        cache: 5
        apiKey: "{{HOMEPAGE_VAR_OPENWEATHER_KEY}}"
    
    - search:
        provider: google
        target: _blank
  
  bookmarks.yaml: |
    - Development:
        - GitHub Repository:
            - abbr: CB
              href: https://github.com/CBunna/kubernetes-homelab
              icon: github.png
              description: My homelab repository
        
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/
              icon: kubernetes.png
              description: Official Kubernetes documentation
        
        - Helm Charts:
            - abbr: Helm
              href: https://artifacthub.io/
              icon: helm.png
              description: Find Helm charts
    
    - Homelab:
        - Router:
            - abbr: RT
              href: https://192.168.1.1
              icon: router.png
              description: Home router admin
        
        - Switch:
            - abbr: SW
              href: https://192.168.1.10
              icon: switch.png
              description: Network switch
        
        - Access Point:
            - abbr: AP
              href: https://192.168.1.11
              icon: wifi.png
              description: Wireless access point
    
    - Documentation:
        - Homepage Docs:
            - abbr: HP
              href: https://gethomepage.dev/
              icon: homepage.png
              description: Homepage documentation
        
        - Docker Hub:
            - abbr: DH
              href: https://hub.docker.com/
              icon: docker.png
              description: Container registry
  
  docker.yaml: ""
  custom.css: |
    /* Custom styles for CBunna's homelab */
    .information-widget-kubernetes .information-widget-kubernetes-cluster,
    .information-widget-kubernetes .information-widget-kubernetes-node {
      background: rgba(var(--color-slate-800), 0.5);
    }
  custom.js: ""