apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Metadata for the kustomization
metadata:
  name: homepage-production

# Base resources to include
resources:
  - ../../base

# Namespace to deploy all resources in
namespace: homepage

# Common labels to add to all resources in addition to the ones from the base
commonLabels:
  environment: production

# Configure any production-specific ConfigMap generators
configMapGenerator:
  - name: homepage-config
    behavior: merge
    literals:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.local,homepage.your-domain.com

# Any patches to apply to the base resources
patchesStrategicMerge:
  - patches/deployment-patch.yaml