apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  TZ: "Europe/Prague"            # Change to your timezone
  DNS1: "1.1.1.1"                # Primary DNS server
  DNS2: "8.8.8.8"                # Secondary DNS server