apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: web
          containerPort: 80
          protocol: TCP
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: TZ
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: WEBPASSWORD
        - name: DNS1
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNS1
        - name: DNS2
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNS2
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: pihole-data
        emptyDir: {}
      - name: dnsmasq-data
        emptyDir: {}